### ISSUE TITLE
Reading to register bug

### ISSUE THREAD

**Issue by olajep** [parallella/oh#17]
IIRC

[0x8e000000] == 0x87654321

``` asm
mov r0, 0
movt r0, 0x8e00
ldrh r0,[r0]
```

This results in r0 now holding 0x8e004321, when it should be 0x00004321.

**Comment by olajep** [comment]
Same applies for bytes

**Comment by aolofsson** [comment]
I don't understand the test case/expected result? Please describe the
sequence of events.

On Wed, Nov 11, 2015 at 7:45 AM, Ola Jeppsson notifications@github.com
wrote:

> Same applies for bytes
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/parallella/oh/issues/17#issuecomment-155767502.

## 

---

Andreas Olofsson, CEO/Founder at Adapteva
Cell: +1 781 325 6688
Twitter: @adapteva
Web: adapteva.com

## Linkedin: linkedin.com/in/andreasolofsson

http://www.adapteva.com/

**Comment by olajep** [comment]
Last line should read
This results in r0 now holding 0x87654321, when it should be 0x00004321.
1. load turns into read access on mesh network
2. packet reaches fpga elink
3. fpga elink sends back write packet w/ higher bits not zeroed out ?
4. packet reaches requesting core and wrong value gets written to register

**Comment by olajep** [comment]
To clarify: This is unrelated to the remapping bug.

**Comment by olajep** [comment]
fixed
