### ISSUE TITLE
interrupt handling

### ISSUE THREAD

**Issue by peteasa** [parallella/oh#25]
Ok I know this is not likely to be hardware ... but I now have an updated epiphany driver running in my kernel that handles the interrupts from the mailbox.  https://github.com/peteasa/examples/tree/parallella-oh/epiphany/mailbox 

Right now I have a strange problem when using it:
I visit each core in the Epiphany chip and from that core write to the mailbox the core id of the core.
In the driver I map the ERX_CFG registers with devm_ioremap_resource() and in the interrupt handler I simply disable the interrupt in ERX_CFG.  In the near future I would like a sysfile with the number of messages pending, but for now I keep it simple and from the command line monitor how many interrupts I have seen using the contents of /proc/interrupts.
Before visiting each core I enable the interrupt in the host application using a new ioctl call to the driver.  After the core has sent the message back via the mailbox I read the number of messages with a call to ee_read_esys() and read the message to clear the source of the interrupt.
After the first core it seems that something goes wrong with the loading of the epiphany code.  So I stopped reading the messages till the end of the run and this is what I get:

``` C
            int mbox_lo     = ee_read_esys(ELINK_MAILBOXLO);
            int mbox_hi     = ee_read_esys(ELINK_MAILBOXHI);
            int post_stat   = ee_read_esys(ELINK_MAILBOXSTAT);
            printf ("main(): PRE_STAT=%08x POST_STAT=%08x LO=%08x HI=%08x\n", pre_stat, post_stat, mbox_lo, mbox_hi);
```

/usr/epiphany/bin/mailbox
main: rows,cols: ( 4, 4)
main:   0: Message from eCore 0x808 ( 0, 0): main: Error in e_load 35476
"Hello World from core 0x808!"
main:   1: Message from eCore 0x809 ( 0, 1): main: Error in e_load 35476
"Hello World from core 0x809!"
main:   2: Message from eCore 0x80a ( 0, 2): main: Error in e_load 35476
...
main(): PRE_STAT=00000001 POST_STAT=00000001 LO=00000808 HI=810f0320
main(): PRE_STAT=00000001 POST_STAT=00000001 LO=00000809 HI=810f0320
main(): PRE_STAT=00000001 POST_STAT=00000001 LO=0000080a HI=810f0320
main(): PRE_STAT=00000001 POST_STAT=00000001 LO=0000080b HI=810f0320
main(): PRE_STAT=00000001 POST_STAT=00000001 LO=00000848 HI=810f0320
main(): PRE_STAT=00000001 POST_STAT=00000001 LO=00000849 HI=810f0320
main(): PRE_STAT=00000001 POST_STAT=00000001 LO=0000084a HI=810f0320
main(): PRE_STAT=00000001 POST_STAT=00000001 LO=0000084b HI=810f0320
...

So for each of the cores I get a message via the mailbox and I also get a good collection of interrupts (actually 17 because I enable the interrupt before checking if I have visited each core)

So this proves that the interrupt handler correctly disables the interrupt and does not affect the user side memory mapping used to read the messages from the cores.

Not sure why when attempting to read the mailbox inside the loop after visiting each core results in failure:

/usr/epiphany/bin/mailbox
main: rows,cols: ( 4, 4)
main(): About to enable interrupt, RxCFG=03e0fe04
[   95.915738] enable mailbox irq
[   95.918780] enable_mailbox_irq: state: 0 rxcfg: 3e0fe04
[   95.924109] enable_mailbox_irq: state: 0 rxcfg after: 13e0fe04
main(): After enable RxCFG=13e0fe04
main:   0: Message from eCore 0x808 ( 0, 0): "Hello World from core 0x808!"
main(): After Interrupt RxCFG=03e0fe04
main(): PRE_STAT=00000001 POST_STAT=00000000 LO=00000808 HI=810f0320
main(): Abo[   96.109023] enable mailbox irq
ut to enable interrupt, RxCFG=03e0fe0c
[   96.117587] enable_mailbox_irq: state: 0 rxcfg: 3e0fe0c
[   96.126361] enable_mailbox_irq: state: 0 rxcfg after: 13e0fe0c
main(): After enable RxCFG=13e0fe0c
main:   1: Message from eCore 0x809 ( 0, 1): ""
main(): After Interrupt RxCFG=13e0fe0c
main(): ERROR: mailbox txfer stopped!

Notice that for some reason I dont get the error in e_load, but also the second e_load does not seem to work because the second core 0x809 does not get a chance to send a mailbox message...  The only thing changed between these two runs is adding the ee_read_esys() for Mailbox Lo and Mailbox Hi at the end after all cores have been visited or after visiting each core. 

Just to show how odd this problem is I have created a second version of the mailbox host program using ee_read_esys / ee_write_esys to enable the interrupts and now I get two complete cycles of my hello world loop before the e_load fails:

/usr/epiphany/bin/mailbox
main: rows,cols: ( 4, 4)
main:   0: Message from eCore 0x808 ( 0, 0): "Hello World from core 0x808!"
main(): PRE_STAT=00000001 POST_STAT=00000000 LO=00000808 HI=810f0320
main:   1: Message from eCore 0x809 ( 0, 1): "Hello World from core 0x809!"
main(): PRE_STAT=00000001 POST_STAT=00000000 LO=00000809 HI=810f0320
main:   2: Message from eCore 0x80a ( 0, 2): ""
main(): ERROR: mailbox txfer stopped!

Any ideas welcome!

**Comment by peteasa** [comment]
By the way the number of messages in the mailbox queue might be of use.

**Comment by aolofsson** [comment]
From the printout it seems that all the cores are printing back Hello
World. Is the concern "Error in e_load 35476"?
Can you send a pointer to the example code?

On Sun, Dec 6, 2015 at 4:35 PM, peteasa notifications@github.com wrote:

> By the way the number of messages in the mailbox queue might be of use.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/parallella/oh/issues/25#issuecomment-162349472.

## 

---

Andreas Olofsson, CEO/Founder at Adapteva
Cell: +1 781 325 6688
Twitter: @adapteva
Web: adapteva.com

## Linkedin: linkedin.com/in/andreasolofsson

http://www.adapteva.com/

**Comment by peteasa** [comment]
All code is available at https://github.com/peteasa/examples/tree/parallella-oh/epiphany/mailbox
New driver see - https://github.com/peteasa/examples/blob/parallella-oh/epiphany/mailbox/kernel/epiphany.c

I guess this driver already answers the earlier issue you have about crashing when the interrupts are switched on!

New test code see - https://github.com/peteasa/examples/blob/parallella-oh/epiphany/mailbox/host/mailbox.c

I am not too worried about the Error in e_load.. more about the failure of the sequence:

```
ee_write_esys(ELINK_RXCFG, rxcfg | (0x1 << 28))
e_load("/usr/epiphany/bin/e_mailbox.srec", &dev, 0, 0, E_TRUE);
** interrupt occurs and in the handler - cfg = reg_read(&mailbox, ERX_CFG);     reg_write(&mailbox, ERX_CFG, cfg & ~MAILBOX_ENABLE);
int items = ee_read_esys(ELINK_MAILBOXSTAT);
ee_read_esys(ELINK_MAILBOXLO);
ee_write_esys(ELINK_RXCFG, rxcfg | (0x1 << 28))
e_load("/usr/epiphany/bin/e_mailbox.srec", &dev, 0, 0, E_TRUE);
***** Hmm.. the core load seems to fail at this point ******
***** so no interrupt and no data ****
xx int items = ee_read_esys(ELINK_MAILBOXSTAT);
xx ee_read_esys(ELINK_MAILBOXLO);
```

The only thing changed between this sequence and the following sequence is removing the ee_read_esys() for Mailbox Lo and Mailbox Hi after each cores has been visited and instead putting this at the very end after all cores have responded... 

The following sequence works just fine:

```
ee_write_esys(ELINK_RXCFG, rxcfg | (0x1 << 28))
e_load("/usr/epiphany/bin/e_mailbox.srec", &dev, 0, 0, E_TRUE);
** interrupt occurs and in the handler - cfg = reg_read(&mailbox, ERX_CFG);     reg_write(&mailbox, ERX_CFG, cfg & ~MAILBOX_ENABLE);
ee_write_esys(ELINK_RXCFG, rxcfg | (0x1 << 28))
e_load("/usr/epiphany/bin/e_mailbox.srec", &dev, 0, 0, E_TRUE);
** interrupt occurs and in the handler - cfg = reg_read(&mailbox, ERX_CFG);     
reg_write(&mailbox, ERX_CFG, cfg & ~MAILBOX_ENABLE);
ee_write_esys(ELINK_RXCFG, rxcfg | (0x1 << 28))
e_load("/usr/epiphany/bin/e_mailbox.srec", &dev, 0, 0, E_TRUE);
** interrupt occurs and in the handler - cfg = reg_read(&mailbox, ERX_CFG);     reg_write(&mailbox, ERX_CFG, cfg & ~MAILBOX_ENABLE);
ee_write_esys(ELINK_RXCFG, rxcfg | (0x1 << 28))
e_load("/usr/epiphany/bin/e_mailbox.srec", &dev, 0, 0, E_TRUE);
....
int items = ee_read_esys(ELINK_MAILBOXSTAT);
ee_read_esys(ELINK_MAILBOXLO);
```

So for each of the cores I get a message via the mailbox and I also get a good collection of interrupts (actually 16 now because I enable the interrupt after checking if I have visited each core)

The final sequence I have published in the above link moves the ee_write_esys(ELINK_RXCFG.. to enable the interrupts after the e_load..

```
e_load("/usr/epiphany/bin/e_mailbox.srec", &dev, 0, 0, E_TRUE);
ee_write_esys(ELINK_RXCFG, rxcfg | (0x1 << 28))
```

This sequence manages two correct mailbox reads then the third fails to e_load.... all very puzzling at the moment.  I will implement the sysfs next and see if the behaviour changes!

**Comment by aolofsson** [comment]
Just to make sure..the MAILBOXSTAT currently only returns not_empty. I see that you read it into "items". The indicator is binary, you will have to poll between every read to see if it's empty. We can change this. Just wanted to make sure there is no spec confusion.

**Comment by peteasa** [comment]
That realization led me to comment "By the way the number of messages in the mailbox queue might be of use."  Anyway I have almost got the epoll event thing working now and I dont think that it depends on a change in entry.  What should happen is that epoll_wait returns when it sees that there is a chance to read a new entry... not sure if it works yet but if not there is a way because commands like tail -f /var/log/messages keep printing the new stuff just added at the end of a file.. same mechanism will allow user side code to see when the interrupt handler has updated the new sysfs file /sys/class/epiphany/epiphany/mailbox_state... more once I have got this going.

**Comment by aolofsson** [comment]
Yes, the concept of having fifo count as a readable quantity is great. Less interrupts to service from host side means more messages / sec once we have this working.:-)

**Comment by peteasa** [comment]
My driver is now working well and the interrupt from the kernel is working... but I still cant get the e_load to work after the mailbox register has been read.  For now I have commented out the code in the interrupt handler that reads the mailbox.. that way, provided you dont read the mailbox on the user side at least you get the interrupt.  The mailbox host program demos the most odd case:

```
create workgroup, e_load,
enable interrupt,
interrupt
disable interrupt,
read lo / hi
create workgroup, e_load
enable interrupt,
interrupt
disable interrupt,
read lo / hi
create workgroup, e_load .... at this point e_load does not seem to work!!
enable interrupt...
timeout.
```

```
# /usr/epiphany/bin/mailbox
InitialEpiphany(): rows,cols: ( 4, 4)
main(): devfd 6, epollfd 5, kernelEventfd 7, cancelfd 8
RunTest():   0: Message from eCore 0x808 ( 0, 0): RunTest(): pre_stat: 1
RunTest(): mbox_lo: 808
RunTest(): mbox_hi: 810f0320
RunTest(): post_stat: 0
"Hello World from core 0x808!"
RunTest():   1: Message from eCore 0x809 ( 0, 1): RunTest(): pre_stat: 1
RunTest(): mbox_lo: 809
RunTest(): mbox_hi: 810f0320
RunTest(): post_stat: 0
"Hello World from core 0x809!"
RunTest():   2: Message from eCore 0x80a ( 0, 2): RunTest(): pre_stat: 0
RunTest(): mbox_lo: 809
RunTest(): mbox_hi: 810f0320
RunTest(): post_stat: 0

INFO: SleepThenCancel(): Cancelling!
```

**Comment by peteasa** [comment]
And I have just found a work round!... Not very pleasant but it works

```
e_reset_system()
create workgroup, e_load,
enable interrupt,
interrupt
disable interrupt,
read lo / hi
e_reset_system()
create workgroup, e_load
enable interrupt,
interrupt
disable interrupt,
read lo / hi
e_reset_system()
create workgroup, e_load .. it continues to work
enable interrupt...
timeout.
```

Not good to have to reset the system but at least it works!  Also it begins to make me suspect a bug to do with the elink interface.

**Comment by peteasa** [comment]
And now that I am looking at the hdl I find a potential issue....

```
# /usr/epiphany/bin/mailbox
InitialEpiphany(): rows,cols: ( 4, 4)
main(): devfd 6, epollfd 5, kernelEventfd 7, cancelfd 8
RunTest():   0: Message from eCore 0x808 ( 0, 0): "Hello World from core 0x808!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=00000808 HI=810f0320
RunTest(): etx_status: f8, erx_status: 808
RunTest():   1: Message from eCore 0x809 ( 0, 1): "Hello World from core 0x809!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=00000809 HI=810f0320
RunTest(): etx_status: f8, erx_status: 809
RunTest():   2: Message from eCore 0x80a ( 0, 2):
INFO: SleepThenCancel(): Cancelling!
INFO: WaitForMailboxNotifier(): Cancelled!
""
RunTest(): etx_status: f8, erx_status: 809
```

In my failing case I find that erx_status is 0x809 ie rxwr_wait is active.. now that can not be good!  This seems to be why I have to reset the system to get things going again.

**Comment by peteasa** [comment]
Now instead of resetting the system I set the first value I read

```
ee_write_esys(ELINK_RXCFG, 0x3e0fe04))
```

and it all works!

So this does seem to be a problem where the ERX_CFG register gets corrupted.. 

```
# /usr/epiphany/bin/mailbox
InitialEpiphany(): rows,cols: ( 4, 4)
main(): devfd 6, epollfd 5, kernelEventfd 7, cancelfd 8
RunTest(): rxcfg register 0x3e0fe04 0x3e0fe04 0x3e0fe04
RunTest():   0: Message from eCore 0x808 ( 0, 0): "Hello World from core 0x808!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=00000808 HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x808, erx_config: 0x3e0fe0c
RunTest(): rxcfg register 0x3e0fe0c 0x3e0fe0c 0x3e0fe0c
RunTest():   1: Message from eCore 0x809 ( 0, 1): "Hello World from core 0x809!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=00000809 HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x809, erx_config: 0x3e0fe0d
RunTest(): rxcfg register 0x3e0fe0d 0x3e0fe0d 0x3e0fe0d
RunTest():   2: Message from eCore 0x80a ( 0, 2): "Hello World from core 0x80a!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=0000080a HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x80a, erx_config: 0x3e0fe0f
RunTest(): rxcfg register 0x3e0fe0f 0x3e0fe0e 0x3e0fe0e
RunTest():   3: Message from eCore 0x80b ( 0, 3): "Hello World from core 0x80b!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=0000080b HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x80b, erx_config: 0x3e0fe0f
RunTest(): rxcfg register 0x3e0fe0f 0x3e0fe0f 0x3e0fe0f
RunTest():   4: Message from eCore 0x848 ( 1, 0): "Hello World from core 0x848!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=00000848 HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x848, erx_config: 0x3e0fe4f
RunTest(): rxcfg register 0x3e0fe4f 0x3e0fe4c 0x3e0fe4c
RunTest():   5: Message from eCore 0x849 ( 1, 1): "Hello World from core 0x849!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=00000849 HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x849, erx_config: 0x3e0fe4d
RunTest(): rxcfg register 0x3e0fe4d 0x3e0fe4d 0x3e0fe4d
RunTest():   6: Message from eCore 0x84a ( 1, 2): "Hello World from core 0x84a!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=0000084a HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x84a, erx_config: 0x3e0fe4f
RunTest(): rxcfg register 0x3e0fe4f 0x3e0fe4e 0x3e0fe4e
RunTest():   7: Message from eCore 0x84b ( 1, 3): "Hello World from core 0x84b!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=0000084b HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x84b, erx_config: 0x3e0fe4f
RunTest(): rxcfg register 0x3e0fe4f 0x3e0fe4f 0x3e0fe4f
RunTest():   8: Message from eCore 0x888 ( 2, 0): "Hello World from core 0x888!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=00000888 HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x888, erx_config: 0x3e0fecf
RunTest(): rxcfg register 0x3e0fecf 0x3e0fe8c 0x3e0fe8c
RunTest():   9: Message from eCore 0x889 ( 2, 1): "Hello World from core 0x889!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=00000889 HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x889, erx_config: 0x3e0fe8d
RunTest(): rxcfg register 0x3e0fe8d 0x3e0fe8d 0x3e0fe8d
RunTest():  10: Message from eCore 0x88a ( 2, 2): "Hello World from core 0x88a!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=0000088a HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x88a, erx_config: 0x3e0fe8f
RunTest(): rxcfg register 0x3e0fe8f 0x3e0fe8e 0x3e0fe8e
RunTest():  11: Message from eCore 0x88b ( 2, 3): "Hello World from core 0x88b!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=0000088b HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x88b, erx_config: 0x3e0fe8f
RunTest(): rxcfg register 0x3e0fe8f 0x3e0fe8f 0x3e0fe8f
RunTest():  12: Message from eCore 0x8c8 ( 3, 0): "Hello World from core 0x8c8!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=000008c8 HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x8c8, erx_config: 0x3e0fecf
RunTest(): rxcfg register 0x3e0fecf 0x3e0fecc 0x3e0fecc
RunTest():  13: Message from eCore 0x8c9 ( 3, 1): "Hello World from core 0x8c9!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=000008c9 HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x8c9, erx_config: 0x3e0fecd
RunTest(): rxcfg register 0x3e0fecd 0x3e0fecd 0x3e0fecd
RunTest():  14: Message from eCore 0x8ca ( 3, 2): "Hello World from core 0x8ca!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=000008ca HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x8ca, erx_config: 0x3e0fecf
RunTest(): rxcfg register 0x3e0fecf 0x3e0fece 0x3e0fece
RunTest():  15: Message from eCore 0x8cb ( 3, 3): "Hello World from core 0x8cb!"
RunTest(): PRE_STAT=00000001 POST_STAT=00000000 LO=000008cb HI=810f0320
RunTest(): etx_status: 0xf8, etx_config: 0x1, erx_status: 0x8cb, erx_config: 0x3e0fecf
RunTest(): rxcfg register 0x3e0fecf 0x3e0fecf 0x3e0fecf
main(): wait for SleepThenCancel thread to terminate
```

**Comment by peteasa** [comment]
Ok so I have created a pull request for you to consider.  I have simulated this and will now try it out on hardware, but the logic is sound.  You may have an alternative way of providing a fix so I have created the pull request now for you to have a look at the proposed fix.

Notice that the OR of 000008cb | 0x3e0fe04 == 0x3e0fecf.. ie both config and emailbox data are active in the ecfg_if.v mi_dout_mux...  My fix filters out the mailbox data thus in the simulation at least fixing the apparent corruption in the register read.

The kernel driver that I have written uses the config register read to do a read modify write to enable / disable the interrupts.  Thus with this bug my kernel driver reads the wrong value from the config register and then writes this whenever the enable / disable of the interrupt is attempted.  This then causes the whole interface to stop functioning... oops!

**Comment by peteasa** [comment]
This fix works with hardware also...  I have now found the next issue to investigate.. The new problem occurs without interrupts.  I made a slight modification to your mailbox test where I loop round multiple times rather than just load one core.  In this problem the e-loader fails during e_start(dev, irow, icol).  The board just locks up and no access is possible.. more later when I have had time to investigate this different problem.

**Comment by aolofsson** [comment]
Thats great! I will review pr tonight. In regards to lockup, just want to
make sure we are in sync on reser sequence. In order to get thw rx readback
to work reliably, you have yo set the idelay to 7. I dont think this is is
in the regular elib yet. I will send an example.

**Comment by peteasa** [comment]
Added a pull request with my changes to the elink/sw/mailbox test.  Also added the driver that I am using today so that anyone can try this out.  The e-main.c file will compile and run with or without the interrupt enabled kernel changes.  The new failure occurs with or without the new interrupt enabled kernel.  To enable interrupts replace the kernel epiphany.c / epiphany.h and rebuild, make sure epiphany.h is in the include path for the e-main.c build and build but change UseInterrupts = 1 in e-main.c and the test will not use a usleep delay but will use interrupts. .. hmm also the device tree needs update adding

<pre>
        elink2_esaxi_0: esaxi@80000000 {
            compatible = "xlnx,parallella-base-1.0";
            interrupt-parent = <&ps7_scugic_0>;
            interrupts = <0 57 4>;
            reg = <0x80000000 0x40000000>;
            xlnx,read-tag-addr = <0x810>;
            };
</pre>

Need to replace the interrupt number and also the interrupt parent reference to match the ones that you have chosen!

**Comment by peteasa** [comment]
closing this issue because it is fixed and the new problem is unrelated to the fix or this issue.
