### ISSUE TITLE
Reading from 0xf02xx regs brpken

### ISSUE THREAD

**Issue by olajep** [parallella/oh#34]
Reading from 0xf02XX regs results in timeout / external fetch abort.

**Comment by aolofsson** [comment]
ok...found the problem. Fixing now.
Andreas

On Mon, Jan 18, 2016 at 8:56 AM, Ola Jeppsson notifications@github.com
wrote:

> Reading from 0xf02XX regs results in timeout / external fetch abort.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/parallella/oh/issues/34.

## 

---

Andreas Olofsson, CEO/Founder at Adapteva
Cell: +1 781 325 6688
Twitter: @adapteva
Web: adapteva.com

## Linkedin: linkedin.com/in/andreasolofsson

http://www.adapteva.com/

**Comment by aolofsson** [comment]
fixed
