### ISSUE TITLE
GPIO: Make GPIO_DIR WR/RD

### ISSUE THREAD

**Issue by olajep** [parallella/oh#59]
Otherwise you need to cache the state somewhere globally

**Comment by olajep** [comment]
Better yet,

Add GPIO_DIRIN and GPIO_DIRIN registers so you can set the direction for individual pins.

```
GPIO_DIRIN:     GPIO_DIR &= ~GPIO_DIRIN
GPIO_DIROUT     GPIO_DIR |= GPIO_DIROUT
```

**Comment by aolofsson** [comment]
closed, added read from GPIO_DIR
